### ISSUE TITLE
Issue Space Marine Cataphractii Terminators

### ISSUE THREAD

**Issue by AenoidThiel** [OnlineCodex/OnlineCodex#161] opened 2018-12-23 12:15 UTC
When you choose the Cataphractiis a issue occur.

**Comment by chisui** [comment] 2018-12-23 17:36
Caused by a `NullPointerException` in `oc.wh40k.units.im.IMSpaceMarinesRuestkammer.refreshen()`

is fixed by #163

**Closed** 2019-06-13 08:50 UTC
Labels: Faction: Imperium, Sub-Faction: Space Marines, bug
